name: Build GoldenCC

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build GoldenCC
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang \
            make \
            git \
            curl \
            perl \
            ldid

      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos

      - name: Install iOS SDKs
        run: |
          git clone https://github.com/theos/sdks.git /tmp/sdks

          mkdir -p $HOME/theos/sdks

          cp -R /tmp/sdks/iPhoneOS16.5.sdk \
            $HOME/theos/sdks/

      - name: Build GoldenCC
        env:
          THEOS: ${{ github.workspace }}/../theos
        run: |
          make clean
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless

      - name: Upload GoldenCC .deb
        uses: actions/upload-artifact@v4
        with:
          name: GoldenCC
          path: packages/*.deb
